version: "3.9"

services:
  client:
    container_name: prakticum-client
    image: ghcr.io/shadow-shamans/first-race/client:d44ca95ebac034d4dc606001225a302c9dc7dbf6
    depends_on:
      - server
    restart: always
    args:
      - CERTBOT_EMAIL=tanotify@gmail.com
      - DOMAIN_LIST=shamans-firstrace-24.ya-praktikum.tech
    ports:
      - 80:80
      - 443:443
    volumes:
      # - ./certbot:/app/letsencrypt:rw
      # - ./var/certchecker:/app/certchecker:rw
      # - ./etc/letsencrypt:/app/letsencrypt2
      - letsencrypt:/etc/letsencrypt

  server:
    container_name: prakticum-server
    image: ghcr.io/shadow-shamans/first-race/server:d44ca95ebac034d4dc606001225a302c9dc7dbf6
    depends_on:
      - postgres
    restart: always
    ports:
      - 3001:3001
    environment:
      NODE_ENV: production

  postgres:
    container_name: prakticum-database
    image: postgres:14
    restart: always
    ports:
      - 5444:5432
    environment:
      POSTGRES_PASSWORD: hsdlkjf4593sdhGh
      POSTGRES_USER: arkanoiduser
      POSTGRES_DB: arkanoiddb
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "sh -c pg_isready -U arkanoiduser -d arkanoiddb" ]
      interval: 10s
      timeout: 3s
      retries: 3

  # certbot:
  #   container_name: certificate
  #   image: certbot/certbot:latest
  #   command: certonly --webroot --webroot-path=/var/certchecker --email tanotify@gmail.com --agree-tos --no-eff-email -d shamans-firstrace-24.ya-praktikum.tech
  #   volumes:
  #     - ./certbot:/etc/letsencrypt:rw
  #     - ./var/certchecker:/var/certchecker:rw

volumes:
  pgdata:
  certificates:
  certbot-www:
