version: "3.9"

services:
  client:
    container_name: prakticum-client
    image: ghcr.io/shadow-shamans/first-race/client:2c9ef5fd4781af581be38e26e55911b67650d313
    depends_on:
      - server
    restart: always
    ports:
      - 80:80
      - 443:443

  server:
    container_name: prakticum-server
    image: ghcr.io/shadow-shamans/first-race/server:2c9ef5fd4781af581be38e26e55911b67650d313
    depends_on:
      - postgres
    restart: always
    ports:
      - 3001:3001
    environment:
      NODE_ENV: production

  postgres:
    container_name: prakticum-database
    image: postgres:14
    restart: always
    ports:
      - 5444:5432
    environment:
      POSTGRES_PASSWORD: hsdlkjf4593sdhGh
      POSTGRES_USER: arkanoiduser
      POSTGRES_DB: arkanoiddb
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "sh -c pg_isready -U arkanoiduser -d arkanoiddb" ]
      interval: 10s
      timeout: 3s
      retries: 3

volumes:
  pgdata:

