version: "3.9"

services:
  client:
    container_name: prakticum-client
    image: ghcr.io/shadow-shamans/first-race/client:732b607470835caa4c155b062252d147dc43a87e
    depends_on:
      - server
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./var/certchecker:/app/certchecker
      - ./certbot:/app/letsencrypt

  server:
    container_name: prakticum-server
    image: ghcr.io/shadow-shamans/first-race/server:732b607470835caa4c155b062252d147dc43a87e
    depends_on:
      - postgres
    restart: always
    ports:
      - 3001:3001
    environment:
      NODE_ENV: production

  postgres:
    container_name: prakticum-database
    image: postgres:14
    restart: always
    ports:
      - 5444:5432
    environment:
      POSTGRES_PASSWORD: hsdlkjf4593sdhGh
      POSTGRES_USER: arkanoiduser
      POSTGRES_DB: arkanoiddb
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "sh -c pg_isready -U arkanoiduser -d arkanoiddb" ]
      interval: 10s
      timeout: 3s
      retries: 3

  certbot:
    container_name: certificate
    image: certbot/certbot:latest
    command: certonly --webroot --webroot-path=/var/certchecker --email tanotify@gmail.com --agree-tos --no-eff-email -d shamans-firstrace-24.ya-praktikum.tech
    volumes:
      - ./certbot:/etc/letsencrypt
      - ./var/certchecker:/var/certchecker

volumes:
  pgdata:
