version: "3.9"

services:
  client:
    container_name: prakticum-client
    image: ghcr.io/shadow-shamans/first-race/client:e24eb6d33ca6be636e6d09e6ff18025c8a710cca
    depends_on:
      - server
    restart: always
    ports:
      - 81:81

  server:
    container_name: prakticum-server
    image: ghcr.io/shadow-shamans/first-race/server:e24eb6d33ca6be636e6d09e6ff18025c8a710cca
    depends_on:
      - postgres
    restart: always
    ports:
      - 3001:3001
    environment:
      NODE_ENV: production

  postgres:
    container_name: prakticum-database
    image: postgres:14
    restart: always
    ports:
      - 5444:5432
    environment:
      POSTGRES_PASSWORD: hsdlkjf4593sdhGh
      POSTGRES_USER: arkanoiduser
      POSTGRES_DB: arkanoiddb
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "sh -c pg_isready -U arkanoiduser -d arkanoiddb" ]
      interval: 10s
      timeout: 3s
      retries: 3

volumes:
  pgdata:
